### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by bloche1871** [YUNG-GANG/YUNGs-Better-Strongholds#3]
1) Could you use the vanilla loot tables for the generated chests? This way mods that add loot to stronghold loottables will be compatible.

2) It seems that the new structures are considered a wholly different structure than strongholds. So for mods like "stronghold compass" for example will be incompatible and fail to detect the strongholds: https://www.curseforge.com/minecraft/mc-mods/stronghold-compass

**Comment by yungnickyoung** [comment]
1. The loot tables are much more extensive and involved than vanilla. You should be able to modify them via datapack if you want to add to them or otherwise modify them. But I can look into adding a config option for having them generate using vanilla tables instead. Do you have any particular mods in mind that modify vanilla stronghold loot tables?
2. It is kind of up to them to add support for my mod, unfortunately. I've tried to make it as compatible as possible with other mods that interface w/ strongholds. You can try opening an issue report with them, but considering they've had an issue report for the same thing with Repurposed Structures open since October 2020, I doubt you'll have much luck.

**Comment by yungnickyoung** [comment]
Opened #7 to address the first issue. The second is, as I said, outside of my control. The onus is on the folks working on the stronghold compass mod to add support for Better Strongholds.
