### ISSUE TITLE
Spawn amount different

### ISSUE THREAD

**Issue by Gregor7008** [YUNG-GANG/YUNGs-Better-Strongholds#51]
As far as I am informed there should be 3 strongholds in a map surrounded by a r=2500 border. But I can find 5?
This is either a bug or intended. If intended: Please publish the new amount!

**Comment by yungnickyoung** [comment]
Better Strongholds loosely follows vanilla stronghold spawning rules, but not exactly. Like vanilla, Better Strongholds spawn in rings extending outward from the center of the world. However, Better Strongholds is more lenient in two ways:

- There is no limit to the number of Better Strongholds spawned per ring. For example, in the first ring, it is possible for more than 3 Better Strongholds to spawn.
- There is no limit to the number of rings. That is, there are infinite rings for strongholds to spawn in (well up until you hit the world border) rather than being capped at 8 rings.

**Comment by Gregor7008** [comment]
Okay then, thank you very much!
