### ISSUE TITLE
Server crashing generating new chunk

### ISSUE THREAD

**Issue by cpereari** [YUNG-GANG/YUNGs-Better-Strongholds#58]
First of all , hi :D ,  TY for taking the time to help me ,  im having some problems with the stronghold mod , cuz  its seems like there are several chunks when i get near it crash the server , and its seems to be  because the strongholds mod , i try remove this mod and the betterdungeon , but  it keep crashing and sending the same error .

I leave here the logs ,  Hope u have a  good day :^D
-  https://paste.shockbyte.com/tuwagatoqakojoyazase.rb

**Comment by cpereari** [comment]
btw , Im playing ate 1.16.5 forge version

**Comment by yungnickyoung** [comment]
Try deleting your Better Strongholds config. It's hard to tell exactly what the issue is from these logs, and unfortunately I don't provide support for 1.16 versions anymore. But you can try asking for help in the [Discord](discord.gg/yung), there are plenty of people in there that may be able to figure out the problem.
