### ISSUE TITLE
End portal doesn't spawn in the Stronghold (1.18.2 / FABRIC v2.1.1)

### ISSUE THREAD

**Issue by Khyzaro** [YUNG-GANG/YUNGs-Better-Strongholds#63]
Hi, i'm actually doing a modpack and i want to use the Stronghold mod.

But a have an issue, the portal **NEVER** spawn in the Stronghold.
(i've done like _10+ worlds_ to test before asking here)

I have zero crash or error command and so i don't know where it's coming.
(the commande `/locate betterstrongholds:stronghold` work and i can tp but there is no portal)

I have already tried differents versions of the Stronghold mod, but nothing change and when i remove the mod, the portal can spawn.

I have differents mods that can maybe conflicts the stronghold mod but i'm not sure (**all fabric and 1.18.2**) : 

_YUNGS BETTER STRONHOLDS v2.1.1_

- **The Graveyard** v1.8   --> I have disabled the Crypt strucures (underground) to prevent any possible grief of the Stronghold
- **BetterEnd** v1.1.0 --> No problem with the dimension
- **BetterNether** v6.1.1
- **Terralith** v2.2.1a
- **Repurposed structures** v4.1.9
- **AdditionalStructures** v.3.0.3

Actually in my modpack, this mod is the only one with an issue and i would love to be able to keep it <3 

Here is my Curseforge modpack link if you want to test : 
[New Dawn v1.5 by Khyzaro-1.18.2.zip](https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/files/8814475/New.Dawn.v1.5.by.Khyzaro-1.18.2.zip)

Thanks you in advance.

Khyzaro

**Comment by Khyzaro** [comment]
fix by adding another portal spawn in the mod config ( 1 -> 2)

**Comment by yungnickyoung** [comment]
To be honest, I suspect this is a matter of you not finding the portal. We've had tens of users report this since the mod's release, and every time it has turned out to be a simple matter of the user being unable to find the portal room. It can be hard to locate, even in spectator mode.

I downloaded your pack to test myself, and indeed every stronghold I found had a portal room.

Feel free to ask for help in the Discord if you still have issues!
