### ISSUE TITLE
Add datapack for paper compattibility

### ISSUE THREAD

**Issue by TheRealGramdalf** [YUNG-GANG/YUNGs-Better-Strongholds#67]
Add a datapack release to enable users who aren't running a modded server to use this mod.

Use case:
Running a crossplay (Java and bedrock edition) server requires using a spigot or equivalent server, which is incompatible with fabric mods. Packaging this as a datapack would allow people to use the mod on such platforms.

**Comment by RowanMaBoot** [comment]
It is possible to use Better Strongholds, along with the other "Better xxx" mods, on Spigot Forks (such as Paper) if you pregenerate the world on the fabric platform with the mods, and then migrate that world save.

However, because there is no associated datapack, logs will be spammed with errors pertaining to invalid references. In the case of Better Strongholds, Eyes of Ender will not lead to the Strongholds. I personally do not know if the invalid reference errors are harmful. They appear to only "fire" once when loading in a chunk with the invalid structure, and do not continue.

Primitive solution (may not be viable, lack of insight from my end):

Would it be possible as to have a datapack with all required structure references, but no support for generation, to serve as a compat bridge? I assume datapacks (versus the fabric implementation) are going to be using very different methods for tackling world generation, so it wouldn't be a "simple port" or viable in that regard.

**Comment by yungnickyoung** [comment]
Unfortunately it's not possible to release my mods as a data pack. They require custom behaviors that are only possible via code.

As for the compat bridge data pack @RowanMaBoot mentioned - that may actually be possible, although I don't plan on creating that myself. Feel free to give it a shot, but just be wary of generating new chunks after you've swapped out the mod for the data pack!

**Comment by TheRealGramdalf** [comment]
Thanks for the replies! I'm really bad at getting back to github issues- some issues with notifications. I may look into doing a datapack, in which case I will definitely release it on github.
